### ISSUE TITLE
USB on Windows(10) slow and unstable

### ISSUE THREAD

**Issue by doewie** [jeelabs/folie#36] opened 2016-12-15 15:43 UTC
I'm afraid there are still (timing?) problems on the USB under W10. Sending a file is very s-l-o-o-o-w ( about 1 line per second) and sometimes characters are not recognized, resulting in 'not found' and 'compile only'-errors.

I'm pretty sure it's in the USB interface, because i'm running the same source files on a setup with HYTiny with ESP-01 breakout board, loaded with firmware ESP-link v2.2.3. This setup runs fast and reliable, even on longer files (> 300 lines) and nested includes.

**Comment by jcw** [comment] 2016-12-15 16:05
Can you describe the setup? What are you sending through & to?
Is the Mecrisp USB driver involved, or is this through a USB-serial interface?

**Comment by doewie** [comment] 2016-12-15 17:06
Setup is pretty basic. Standard JeeLabs USB FTDI. GND, 5V and TX/RX(crossed) connected to HyTiny.
Driver: by FTDI, dated 09-03-2016, version 2.12.16.0.

With same setup i flashed the latest Mecrisp-Stellaris RA 2.3.1 for STM32F103 with [STM32 Flash Loader Demonstrator ](http://www.st.com/content/st_com/en/products/development-tools/software-development-tools/stm32-software-development-tools/stm32-programmers/flasher-stm32.html#) fast without any problems, so basically it works fine.

Running folie 2.7 with -r option. Folie sees the COM-port, which is connected after selection
```
Select the serial port:
  1: COM6
   1
? Enter '!help' for additional help, or ctrl-d to quit.
[connected to COM6]
```
then 2 very short Forth files:
a.fs
```
include b.fs
: run ( -- ) 
	hello 
;
```
and b.fs
```
: hello ( -- ) 
	CR ." hello" 
;
```
sending (!s) the main file (a.fs)
```
!s a.fs
2> b.fs 2:  CR ." hello"   ok.
1> a.fs 3:  hello   ok.
run
hello ok.
```
So this one is OK. But at very low speed, approx. 1 line/sec, and sometimes with errors,

**Comment by SevenW** [comment] 2017-01-15 13:51
I may have something related with serial communication from Windows to a HyTiny programmed as a SerPlus.
```
!s core.fs
1> core.fs 3: <<<board>>>

Finished. Reset Mecrisp-Stellaris RA 2.3.1 with M0 core for STM32L053C8 by Matthias Koch
64 KB <jnz> 3238022E ram/flash: 6816 32512 free ok.
1> core.fs 4: cr compiletoflash
 ok.
1> core.fs 5: ( core start: ) 00008100  ok.
2> rf69.fs 50: create rf:init  \ initialise the radio, each 16-bit word is  (timeout)
Send failed.
<reg#,val>  ok.
```
Here the problem appears to be a (timeout) generated by Folie v2.8. This timeout is fixed a t 1s. 
When I send a file to the JNZv3, through the serPlus, then by far most of the lines take just below one second to get compiled. But in a longer forth file, such as core.fs for in embello folder jz3, there are some lines that take more then 1s, giving the (timeout)

To me this seems to be a windows USB driver / Mecrisp+USBdrive in the HyTiny issue.

SevenW

**Comment by SevenW** [comment] 2017-01-18 08:40
I further analyzed slow file sends on windows. A USB trace analyzer indicates that folie.exe waits for one second exactly between commands. This happens after `ok..` has been received, and before the next command is send.

I expect it to happen in the match function in include.go. It reads a full reply line there, and maybe windows is just waiting for another CR or whatever never to arrive after it has received the `ok..` string. Then the one-second timeout of go-serial may kick in.
go serial timeout:
https://github.com/bugst/go-serial/blob/43fc80d807eea385cf4d60be922b6a2f61508340/serial_windows.go#L358

match function:
https://github.com/jeelabs/folie/blob/master/include.go#L83

The match function has also a timeout, but that does not kick in in the upload of my 6-line dim.fs program.

I will add traces when I figured out how to do. But they require some experience to interpret.

I have demonstrated with Forth Explorer (fe.py) from Mecrisp that the one second wait does not occur in this program.

**Comment by SevenW** [comment] 2017-01-18 08:44
Traces expored to CSV,
[serplus-jnz3-folie-dim-sendfile.zip](https://github.com/jeelabs/folie/files/713375/serplus-jnz3-folie-dim-sendfile.zip)

**Comment by SevenW** [comment] 2017-01-18 09:38
My current guess is that in windows the match function is always left on the timer-fired case:
https://github.com/jeelabs/folie/blob/master/include.go#L141
and never true the intended:
https://github.com/jeelabs/folie/blob/master/include.go#L133

_This might also be the case on linux, but without a timeout in the serial code!_

Could you verify that?

Then why would we not pass this condition:
https://github.com/jeelabs/folie/blob/master/include.go#L115

Maybe because the code with splitting the lines is incorrect? I have difficulties to understand this. It seems to be correct.

**Comment by SevenW** [comment] 2017-01-19 07:51
I tracked down the issue in the go-serial module. In our used case Read(0 and Write() to usb-serial devices happen at the same time (concurrent) but it seems Windows handles them sequentially. The slowness is caused by calling Read() and immediatly after that calling Write() to send the next line.

The go-serial module implements a timeout on the Read() function of one second. As nonew charaters are currently arriving from the target, Read() (internally in go-serial) times out after one second, and only then the Write() action actually takes place. Hence the one-line-per-second behaviour.

I informed the owner of the serial package of my findings, and I made modification without timeout that I am currently testing. Speed is now about 1.3-2.0 times slower then on the Raspberry pi.

**Comment by doewie** [comment] 2017-01-20 06:20
I just applied the latest patch in the go-serial package (https://github.com/bugst/go-serial/pull/16) and can confirm that on my W10 everything now runs very smoothly. Not only sending files is running fast now, but also uploading new images.
Great!!, and many thanks to everybody involved

**Comment by jcw** [comment] 2017-01-20 10:04
Fantastic resolution, closing this issue. I'll update Folie in the next release cycle.

**Closed by jcw** 2017-01-20 10:04 UTC
Labels: bug, windows
