### ISSUE TITLE
USB serial drops out -windows

### ISSUE THREAD

**Issue by festan** [jeelabs/folie#47] opened 2017-02-15 08:49 UTC
In Windows (7 & 10) when running a user defined word USB serial drops out. Transcript and resulting error below:

c:\jeelabs>folie -r

  1: COM1
  2: COM3
The filename, directory name, or volume label syntax is incorrect.
2
Enter '!help' for additional help, or ctrl-d to quit.
[connected to COM3]
  ok.
  ok.
: toggle-me    begin pc13 iox! 250 ms key? until ;  ok.
omode-pp pc13 io-mode!  ok.
toggle-me
[disconnected] Invalid serial port
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x4c1707]

goroutine 7 [running]:
panic(0x5fd3a0, 0x10d20030)
        /usr/local/Cellar/go/1.7.4_2/libexec/src/runtime/panic.go:500 +0x331
go.bug.st/serial%2ev1.(*windowsPort).Write(0x0, 0x10db09a0, 0x1, 0x8, 0x0, 0x0, 0x0)
        /Users/jcw/Go/src/go.bug.st/serial.v1/serial_windows.go:114 +0x97
main.SerialDispatch.func1()
        /Users/jcw/Go/src/github.com/jeelabs/folie/serial.go:118 +0x1d2
created by main.SerialDispatch
        /Users/jcw/Go/src/github.com/jeelabs/folie/serial.go:128 +0x4a

c:\jeelabs>

**Comment by martynj3** [comment] 2017-02-15 09:58
Does it work if you avoid using  pin13?
 

    On Wednesday, February 15, 2017 4:49 PM, festan <notifications@github.com> wrote:
 

 In Windows (7 & 10) when running a user defined word USB serial drops out. Transcript and resulting error below:c:\jeelabs>folie -r1: COM1
2: COM3
The filename, directory name, or volume label syntax is incorrect.
2
Enter '!help' for additional help, or ctrl-d to quit.
[connected to COM3]
ok.
ok.
: toggle-me begin pc13 iox! 250 ms key? until ; ok.
omode-pp pc13 io-mode! ok.
toggle-me
[disconnected] Invalid serial port
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x4c1707]goroutine 7 [running]:
panic(0x5fd3a0, 0x10d20030)
/usr/local/Cellar/go/1.7.4_2/libexec/src/runtime/panic.go:500 +0x331
go.bug.st/serial%2ev1.(*windowsPort).Write(0x0, 0x10db09a0, 0x1, 0x8, 0x0, 0x0, 0x0)
/Users/jcw/Go/src/go.bug.st/serial.v1/serial_windows.go:114 +0x97
main.SerialDispatch.func1()
/Users/jcw/Go/src/github.com/jeelabs/folie/serial.go:118 +0x1d2
created by main.SerialDispatch
/Users/jcw/Go/src/github.com/jeelabs/folie/serial.go:128 +0x4ac:\jeelabs>—

**Comment by doewie** [comment] 2017-02-15 10:15
Is there  any chance you are not running the latest version of Folie with the latest version of the go.bug.st/serial.v1 package?
This line in your output 
`The filename, directory name, or volume label syntax is incorrect.`
reminds me of one of the first problems I had on W10

**Comment by doewie** [comment] 2017-02-15 13:37
Just reproduced the same error on W10 with a Blue Pill running [usb-common.bin](https://github.com/jeelabs/embello/blob/master/explore/1608-forth/suf/usb-common.bin)
```
toggle-me
[disconnected] Invalid serial port
```

Running same code on Blue Pill ser2plus -> HyTiny: No errors.

**Comment by jcw** [comment] 2017-05-01 12:54
FWIW, I've uploaded a new [v2.11 release](https://github.com/jeelabs/folie/releases/tag/v2.11), with latest serial and readline (and Mecrisp images).

**Comment by jcw** [comment] 2017-05-17 14:06
Ah, wait - this is probably due to USB getting disconnected due to long gaps between polling the USB driver. It might work better with the multitasker enabled, i.e. when the `usb-poll`  word gets called more often. Another thing to try, with the multitasker _not_ enabled is:

    ' usb-poll hook-pause !

Which should have the same effect: keep the USB driver polling during `ms` delays.

**Comment by festan** [comment] 2017-05-18 09:27
Just tested on windows with the above suggestions and indeed it does work both in the multitasker and with the hook-pause work-around.

I've taken to running Linux in a virtual machine on windows to avoid these small issues now. Once I become more familiar with Linux and the command line it might be time to give windows the ol' heave-ho...

**Comment by jcw** [comment] 2017-05-18 09:30
Ok, great - thanks for checking. I'll close this for now.

**Closed by jcw** 2017-05-18 09:30 UTC
Labels: windows
